# -*- coding: utf-8 -*-
"""Customer_Churn_Analysis_Modified.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1odQF_Guj0iWUQzDcJOmxO6Ek2zH1Lzqe

Importing Libraries
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from random import randint

"""Generate Synthetic Dataset"""

rng_seed = 42
np.random.seed(rng_seed)

n = 100000

data = pd.DataFrame({
    "Customer_ID": range(1, n+1),
    "Age": np.random.randint(18, 70, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Tenure": np.random.randint(0, 11, n),
    "Balance": np.random.randint(0, 200000, n),
    "CreditScore": np.random.randint(300, 901, n),
    "EstimatedSalary": np.random.randint(10000, 150001, n),
    "NumOfProducts": np.random.randint(1, 5, n),
    "IsActiveMember": np.random.choice([0, 1], n)
})


data["Churn"] = (
    (data["Balance"] < 50000).astype(int) +
    (data["IsActiveMember"] == 0).astype(int) +
    (data["CreditScore"] < 500).astype(int)
)

data["Churn"] = data["Churn"].apply(lambda x: 1 if x >= 2 else 0)

print(data.head())

"""Data Cleaning & Preprocessing"""

# Check missing values
missing_values = data.isnull().sum()
print(missing_values)

# Data types
column_types = data.dtypes
print(column_types)

# Encode Gender
data["Gender"] = data["Gender"].map({"Male": 0, "Female": 1})

"""Descriptive Statistics"""

print("Mean:\n", data.mean(numeric_only=True))
print("\nMedian:\n", data.median(numeric_only=True))
print("\nStd Dev:\n", data.std(numeric_only=True))

# Mode
print("\nMode:\n", data.mode().iloc[0])

"""Churn Behavior Analysis"""

churn_rate = data["Churn"].value_counts(normalize=True).sort_index()
print(churn_rate.sort_index())

# Compare churn vs non-churn
print(data.groupby("Churn").mean(numeric_only=True))

"""Group-Based Analysis"""

# Age group
data["AgeGroup"] = pd.cut(data["Age"], bins=[18,30,45,60,70],
                         labels=["18-30","30-45","45-60","60-70"])

print(data.groupby("AgeGroup")["Churn"].mean())

# Gender vs churn
print(data.groupby("Gender")["Churn"].mean())

# Active vs churn
print(data.groupby("IsActiveMember")["Churn"].mean())

# Products vs churn
print(data.groupby("NumOfProducts")["Churn"].mean())

"""Relationship Analysis"""

print(data[["Balance", "Churn"]].corr())
print(data[["CreditScore", "Churn"]].corr())
print(data[["Tenure", "Churn"]].corr())

"""Data Visualization"""

sns.countplot(x="Churn", data=data)
plt.title("Churn Distribution")
plt.show()

data["Churn"].value_counts().plot.pie(autopct="%1.1f%%")
plt.title("Churn Percentage")
plt.show()

data["Age"].hist(bins=30)
plt.title("Age Distribution")
plt.show()

plt.scatter(data["Balance"], data["EstimatedSalary"], alpha=0.3)
plt.xlabel("Balance")
plt.ylabel("Salary")
plt.title("Balance vs Salary")
plt.show()

sns.boxplot(x="Churn", y="Balance", data=data)
plt.title("Balance vs Churn")
plt.show()

corr = data.select_dtypes(include=np.number).corr()
sns.heatmap(corr, annot=True, fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

print("Insights:")
print("- Customers with low balance are more likely to churn.")
print("- Inactive members have higher churn rate.")
print("- Low credit score increases churn risk.")
print("- Customers with fewer products tend to leave more.")